### ISSUE TITLE
undefined reference to `crypt_gensalt_rn'

### ISSUE THREAD

**Issue by xuelanghu120** [rg3/bcrypt#10]
E:\download\bcrypt_ndk-master\bcrypt_ndk-master\app\src\main\cpp\bcrypt/bcrypt.c:119: undefined reference to `crypt_gensalt_rn'
CMakeFiles/bcrypt.dir/src/main/cpp/bcrypt/bcrypt.c.o: In function `bcrypt_hashpw':
E:\download\bcrypt_ndk-master\bcrypt_ndk-master\app\src\main\cpp\bcrypt/bcrypt.c:127: undefined reference to `crypt_rn'
clang.exe: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by rg3** [comment]
Ninja build system? Windows? I believe you may have reported the issue in the wrong project. If I had to guess, maybe this is the one you're looking for:

https://github.com/adisorns09244/bcrypt_ndk
