### ISSUE TITLE
Requirement of bcrypt library for ARM

### ISSUE THREAD

**Issue by Arjun-Padmanabhan** [rg3/bcrypt#7]
Is it possible to cross -compile bcrypt library for ARM?

I have tried compiling but in bcrypt/crypt_blowfish/Makefile i see we are including x86.o?

**Comment by Arjun-Padmanabhan** [comment]
Update: I tried removing x86.o from makefile and could obtain cross-compiled bcrypt.a . But what was the significance of x86.o?

**Comment by rg3** [comment]
The crypt_blowfish subdirectory is a verbatim copy of the crypt_blowfish bcrypt implementation as can be found here:

http://www.openwall.com/crypt/

Which is what my library wraps. I've never tried to compile this code under non-x86 platforms, but crypt_blowfish/README makes a small mention that the project should compile on non-x86 platforms producing no code from x86.S.

I suggest you try to compile crypt_blowfish as a standalone project first and, if you find trouble building it from the Makefile, contact Solar Designer directly.
